# Docs:
# https://aka.ms/yaml

trigger:
  - master
pool:
  name: Hosted Ubuntu 1604
steps:
- task: AzureCLI@1
  displayName: 'Azure CLI '
  inputs:
    azureSubscription: 'DCD-CFTAPPS-SBOX'
    scriptLocation: inlineScript
    inlineScript: |
      diskID=$(az disk create -g aks-infra-sbox-rg -n jenkins-disk --size-gb 1024 --sku Premium_LRS --location uksouth | jq .id |sed 's/\"//g')
      az keyvault secret set --vault-name "cftapps-sbox" --name "jenkins-disk-id" --value $diskID
      echo "Jenkins disk ID stored in Vault: https://cftapps-sbox.vault.azure.net/secrets/jenkins-disk-id "
  