# Docs:
# https://aka.ms/yaml

trigger:
  - master
pool:
  name: Hosted Ubuntu 1604
steps:
- task: AzureCLI@1
  displayName: 'Azure CLI '
  inputs:
    azureSubscription: 'DCD-CFTAPPS-SBOX (aks-infra-sbox)'
    scriptLocation: inlineScript
    #inlineScript: 'az disk create -g aks-infra-sbox-rg -n jenkins-disk --size-gb 1024 --sku Premium_LRS --location uksouth'
    inlineScript: 'az disk create -g aks-infra-sbox-rg -n jenkins-disk --size-gb 10 --sku Premium_LRS --location uksouth'