parameters:
  azureSubscription: ''
  keyvaultName: ''
  ResourceGroup: ''

jobs:
- job: RunBootstrap
  timeoutInMinutes: 60
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - task: AzureCLI@1
    displayName: 'Azure CLI '
    inputs:
      azureSubscription: ${{ parameters.azureSubscription }}
      scriptLocation: inlineScript
      inlineScript: |
        diskID=$(az disk create -g ${{ parameters.ResourceGroup }} -n jenkins-disk --size-gb 1024 --sku Premium_LRS --location uksouth | jq .id |sed 's/\"//g')
        az keyvault secret set --vault-name ${{ parameters.keyvaultName }} --name "jenkins-disk-id" --value $diskID

